# Generated by Django 4.1.7 on 2023-04-06 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='query',
            name='subject',
            field=models.CharField(max_length=500),
        ),
    ]
