# Generated by Django 4.1.7 on 2023-02-23 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0003_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(choices=[], max_length=255)),
                ('name', models.CharField(max_length=100)),
                ('code', models.IntegerField()),
            ],
        ),
    ]
