# Generated by Django 4.1.7 on 2023-02-24 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0008_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='country',
            field=models.CharField(choices=[('INDIA', 'INDIA')], max_length=255),
        ),
        migrations.AlterField(
            model_name='state',
            name='country',
            field=models.CharField(choices=[('INDIA', 'INDIA')], max_length=255),
        ),
    ]
