# Generated by Django 4.1.7 on 2023-02-25 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0009_alter_city_country_alter_state_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('MEN', 'MEN'), ('WOMEN', 'WOMEN'), ('KIDS', 'KIDS'), ('HOME', 'HOME'), ('ALL', 'ALL')], max_length=255),
        ),
        migrations.AlterField(
            model_name='item',
            name='service',
            field=models.CharField(choices=[('STEAM IRON', 'STEAM IRON'), ('DRY CLEANING', 'DRY CLEANING'), ('WASHING AND IRON', 'WASHING AND IRON'), ('WASH AND FOLD', 'WASH AND FOLD')], max_length=255),
        ),
    ]
