# Generated by Django 4.1.7 on 2023-02-27 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0010_alter_item_category_alter_item_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
            ],
        ),
    ]
