# Generated by Django 4.1.7 on 2023-03-01 09:07

from django.db import migrations, models
from django.utils import timezone



class Migration(migrations.Migration):

    dependencies = [
        ('master', '0012_order_item_alter_order_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date_ordered',
            field=models.DateTimeField(auto_now_add=True, default=timezone.now),
        ),
    ]
