# Generated by Django 4.1.7 on 2023-03-02 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0015_order_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(default='1234', max_length=10, unique=True),
        ),
    ]
