# Generated by Django 4.1.7 on 2023-03-02 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0018_alter_order_order_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_number',
        ),
    ]
