# Generated by Django 4.1.7 on 2023-03-20 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0020_order_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='state',
            field=models.CharField(choices=[('HARYANA', 'HARYANA')], max_length=255),
        ),
    ]
