# Generated by Django 4.1.7 on 2023-03-20 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0021_alter_city_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='city',
            field=models.CharField(choices=[('GURUGRAM', 'GURUGRAM')], max_length=255),
        ),
    ]
