# Generated by Django 4.1.7 on 2023-03-20 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0022_alter_area_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='city',
            field=models.CharField(choices=[('GURUGRAM', 'GURUGRAM'), ('PANIPAT', 'PANIPAT')], max_length=255),
        ),
    ]
