# Generated by Django 4.1.7 on 2023-03-21 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0026_order_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
